# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
        script: |
          cd ~/evadia
          git pull
          cd ~/evadia/front
          npm install && npm run build
          cp -r ~/evadia/front/dist/* /var/www/evadia/
          cp -r ~/evadia/back/* ~/evadia-api/
          cd ~/evadia-api/
          npm install
          pm2 reload API
          echo 'Deployed successfully to Digital Ocean server'
    
